# ===== 1) Build stage =====
FROM node:22-alpine AS build
WORKDIR /app

# Lepszy cache: najpierw tylko manifesty
COPY package*.json ./
RUN npm ci && npm i -g @angular/cli@17

# Potem reszta źródeł
COPY . .

# Produkcyjny build (Angular 15+)
RUN ng build --configuration=production

# ===== 2) Runtime (Nginx) =====
FROM nginx:1-alpine AS runtime
LABEL author="263855"

COPY --from=build /app/dist/*/browser/ /usr/share/nginx/html/


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
